In [573]:
import numpy as np
import pandas as pd
import random


### Get the dimention of the block

In [574]:
n = 10
array = np.random.randint(low=1, high=5, size=(n, n))

In [575]:
colour_hash = [1,2,3,4]

In [576]:
array

array([[1, 4, 3, 4, 2, 1, 3, 4, 4, 2],
       [1, 1, 2, 2, 4, 4, 2, 2, 4, 1],
       [3, 3, 3, 1, 4, 2, 3, 1, 3, 4],
       [3, 1, 4, 2, 2, 3, 3, 3, 2, 1],
       [4, 2, 4, 1, 2, 4, 1, 4, 3, 2],
       [4, 2, 1, 1, 1, 1, 3, 3, 1, 3],
       [2, 2, 4, 2, 1, 1, 2, 1, 4, 3],
       [4, 1, 3, 2, 4, 3, 2, 2, 3, 2],
       [3, 1, 2, 2, 2, 1, 4, 4, 3, 3],
       [2, 4, 2, 4, 1, 2, 4, 3, 3, 3]])

In [577]:
array[1][1]

1

### Get Adjacent Blocks and its Color

In [630]:
def get_adjusent(array, i_row, j_column):
    
    neighbours = {}
    
    try:
        left_element = i_row, j_column - 1
        neighbours[left_element] = (array[left_element[0], left_element[1]])

    except IndexError:
        pass
        
    try: 
        right_element = i_row, j_column + 1
        neighbours[right_element] = (array[right_element[0], right_element[1]])
    
    except IndexError:
        pass
        
    try:
        up_element = i_row - 1, j_column
        neighbours[up_element] = (array[up_element[0], up_element[1]])
   
    except IndexError:
        pass
    
    try:
        down_element = i_row + 1, j_column
        neighbours[down_element] = (array[down_element[0], down_element[1]])

    except IndexError:
        pass

    # Removing the negative index(-1) neighbour
    marker = []
    for i in neighbours.keys():
        if -1 in i:
            marker.append(i)
    if marker != []:
        for i in marker:
            del neighbours[i]    

    return neighbours
    
    

In [664]:
a = np.random.randint(low=1, high=5, size=(n, n))

In [665]:
a

array([[1, 3, 1, 3, 4, 4, 3, 1, 4, 1],
       [4, 1, 2, 1, 2, 2, 3, 4, 3, 4],
       [4, 2, 4, 1, 4, 3, 3, 4, 1, 1],
       [3, 4, 1, 4, 1, 4, 1, 1, 4, 4],
       [1, 3, 1, 2, 3, 3, 4, 4, 3, 1],
       [3, 3, 1, 3, 4, 3, 2, 2, 3, 4],
       [3, 2, 3, 3, 3, 2, 3, 4, 4, 1],
       [4, 2, 3, 2, 4, 1, 1, 3, 1, 2],
       [1, 2, 3, 4, 3, 2, 1, 3, 4, 2],
       [2, 1, 4, 2, 1, 4, 4, 4, 4, 1]])

In [658]:
i = 1
j = 1

In [659]:
a = array[i][j]

In [660]:
array

array([[1, 4, 3, 4, 2, 1, 3, 4, 4, 2],
       [1, 1, 2, 2, 4, 4, 2, 2, 4, 1],
       [3, 3, 3, 1, 4, 2, 3, 1, 3, 4],
       [3, 1, 4, 2, 2, 3, 3, 3, 2, 1],
       [4, 2, 4, 1, 2, 4, 1, 4, 3, 2],
       [4, 2, 1, 1, 1, 1, 3, 3, 1, 3],
       [2, 2, 4, 2, 1, 1, 2, 1, 4, 3],
       [4, 1, 3, 2, 4, 3, 2, 2, 3, 2],
       [3, 1, 2, 2, 2, 1, 4, 4, 3, 3],
       [2, 4, 2, 4, 1, 2, 4, 3, 3, 3]])

In [661]:
adjusent_to_a = get_adjusent(array, i, j )

In [662]:
adjusent_to_a

{(1, 0): 1, (1, 2): 2, (0, 1): 4, (2, 1): 3}

In [663]:
len(adjusent_to_a.values())

4

In [437]:
array[i, j]

1

### Fitness Function

In [593]:
def fitness_func(array):
    fitness_value_hash = {}
    for index, x in np.ndenumerate(array):
        
        fitness_value_each_element = 0
        
        adjusent_to_x = get_adjusent(array, *index)
        for colour in adjusent_to_x.values():
            if colour == x:
                fitness_value_each_element += 1
        
        fitness_value_hash[index] = fitness_value_each_element
 #       print(f"Element Index {index}, Fitness Value {fitness_value_each_element}")
    
    fitness_value_hash_sorted = {k: v for k, v in sorted(fitness_value_hash.items(), key=lambda item: item[1], reverse=True)}

    return fitness_value_hash_sorted

In [594]:
array

array([[1, 4, 3, 4, 2, 1, 3, 4, 4, 2],
       [1, 1, 2, 2, 4, 4, 2, 2, 4, 1],
       [3, 3, 3, 1, 4, 2, 3, 1, 3, 4],
       [3, 1, 4, 2, 2, 3, 3, 3, 2, 1],
       [4, 2, 4, 1, 2, 4, 1, 4, 3, 2],
       [4, 2, 1, 1, 1, 1, 3, 3, 1, 3],
       [2, 2, 4, 2, 1, 1, 2, 1, 4, 3],
       [4, 1, 3, 2, 4, 3, 2, 2, 3, 2],
       [3, 1, 2, 2, 2, 1, 4, 4, 3, 3],
       [2, 4, 2, 4, 1, 2, 4, 3, 3, 3]])

In [628]:
fitness_hash = fitness_func(array)

In [629]:
fitness_hash

{(3, 6): 3,
 (5, 3): 3,
 (5, 4): 3,
 (8, 3): 3,
 (8, 8): 3,
 (9, 8): 3,
 (0, 8): 2,
 (1, 0): 2,
 (1, 4): 2,
 (2, 0): 2,
 (2, 1): 2,
 (3, 4): 2,
 (5, 1): 2,
 (5, 5): 2,
 (6, 1): 2,
 (6, 4): 2,
 (6, 5): 2,
 (7, 3): 2,
 (7, 6): 2,
 (8, 2): 2,
 (8, 6): 2,
 (8, 9): 2,
 (9, 9): 2,
 (0, 0): 1,
 (0, 7): 1,
 (1, 1): 1,
 (1, 2): 1,
 (1, 3): 1,
 (1, 5): 1,
 (1, 6): 1,
 (1, 7): 1,
 (1, 8): 1,
 (2, 2): 1,
 (2, 4): 1,
 (2, 6): 1,
 (3, 0): 1,
 (3, 2): 1,
 (3, 3): 1,
 (3, 5): 1,
 (3, 7): 1,
 (4, 0): 1,
 (4, 1): 1,
 (4, 2): 1,
 (4, 3): 1,
 (4, 4): 1,
 (5, 0): 1,
 (5, 2): 1,
 (5, 6): 1,
 (5, 7): 1,
 (5, 9): 1,
 (6, 0): 1,
 (6, 3): 1,
 (6, 6): 1,
 (6, 9): 1,
 (7, 1): 1,
 (7, 7): 1,
 (7, 8): 1,
 (8, 1): 1,
 (8, 4): 1,
 (8, 7): 1,
 (9, 2): 1,
 (9, 6): 1,
 (9, 7): 1,
 (0, 1): 0,
 (0, 2): 0,
 (0, 3): 0,
 (0, 4): 0,
 (0, 5): 0,
 (0, 6): 0,
 (0, 9): 0,
 (1, 9): 0,
 (2, 3): 0,
 (2, 5): 0,
 (2, 7): 0,
 (2, 8): 0,
 (2, 9): 0,
 (3, 1): 0,
 (3, 8): 0,
 (3, 9): 0,
 (4, 5): 0,
 (4, 6): 0,
 (4, 7): 0,
 (4, 8): 0,
 (4,

### Selection Function

In [588]:
def selection(array):
    fitness_hash = fitness_func(array)

    impure_items = {}
    for i in fitness_hash:
        if fitness_hash[i] != 0:
            impure_items[i] = fitness_hash[i]
 #           print(impure_items)    

    all_imp_elements = impure_items.keys()
    all_imp_rows = set([i[0] for i in all_imp_elements])
    all_imp_col = set([i[1] for i in all_imp_elements])
    
    return all_imp_elements, all_imp_rows, all_imp_col

In [621]:
all_imp_elements, all_imp_rows, all_imp_col = selection(array)

In [622]:
all_imp_elements

dict_keys([(3, 6), (5, 3), (5, 4), (8, 3), (8, 8), (9, 8), (0, 8), (1, 0), (1, 4), (2, 0), (2, 1), (3, 4), (5, 1), (5, 5), (6, 1), (6, 4), (6, 5), (7, 3), (7, 6), (8, 2), (8, 6), (8, 9), (9, 9), (0, 0), (0, 7), (1, 1), (1, 2), (1, 3), (1, 5), (1, 6), (1, 7), (1, 8), (2, 2), (2, 4), (2, 6), (3, 0), (3, 2), (3, 3), (3, 5), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (5, 0), (5, 2), (5, 6), (5, 7), (5, 9), (6, 0), (6, 3), (6, 6), (6, 9), (7, 1), (7, 7), (7, 8), (8, 1), (8, 4), (8, 7), (9, 2), (9, 6), (9, 7)])

In [623]:
all_imp_rows

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [624]:
all_imp_col

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [625]:
array

array([[1, 4, 3, 4, 2, 1, 3, 4, 4, 2],
       [1, 1, 2, 2, 4, 4, 2, 2, 4, 1],
       [3, 3, 3, 1, 4, 2, 3, 1, 3, 4],
       [3, 1, 4, 2, 2, 3, 3, 3, 2, 1],
       [4, 2, 4, 1, 2, 4, 1, 4, 3, 2],
       [4, 2, 1, 1, 1, 1, 3, 3, 1, 3],
       [2, 2, 4, 2, 1, 1, 2, 1, 4, 3],
       [4, 1, 3, 2, 4, 3, 2, 2, 3, 2],
       [3, 1, 2, 2, 2, 1, 4, 4, 3, 3],
       [2, 4, 2, 4, 1, 2, 4, 3, 3, 3]])

### Crossover Function

In [508]:
def crossover_function(array, all_imp_elements, all_imp_rows, all_imp_col, colour_hash=colour_hash):
    
    set_new_offspring = []
    for element in all_imp_elements:
        
        new_array = array.copy()
        mycol_hash = colour_hash.copy()
        
        present_color = array[element]
        mycol_hash.remove(present_color)

        
        new_color = random.choice(mycol_hash)
        new_array[element] = new_color
        set_new_offspring.append(new_array)

        new_array = array.copy()
        mycol_hash = colour_hash.copy()
        
        #print(sum(fitness_func(new_array).values()))
    return set_new_offspring

### Main Function

In [556]:
n = 10
array = np.random.randint(low=1, high=5, size=(n, n))
colour_hash = [1,2,3,4]

In [559]:
max_count = 1000

def start_checking(array):
    
    global max_count    
    new_arrays = []
    
    if max_count < 0:
        return new_arrays
    else:
        all_imp_elements, all_imp_rows, all_imp_col = selection(array)
        new_arrays = crossover_function(array, all_imp_elements, all_imp_rows, all_imp_col)

        for a in new_arrays:
            if sum(fitness_func(a).values()) <=4 :
                return a  
            else:
                
                max_count -= 1
                if max_count < 0:
                    return new_arrays[-1]
                else:
                    print(max_count, sum(fitness_func(a).values()))
                    start_checking(a) 
    

In [560]:
abc = start_checking(array)

999 88
998 86
997 84
996 78
995 74
994 74
993 70
992 70
991 70
990 66
989 62
988 58
987 54
986 50
985 50
984 48
983 46
982 44
981 42
980 40
979 38
978 36
977 34
976 34
975 32
974 36
973 30
972 28
971 26
970 26
969 26
968 22
967 22
966 22
965 22
964 20
963 20
962 20
961 20
960 18
959 16
958 16
957 20
956 14
955 16
954 14
953 16
952 12
951 10
950 10
949 10
948 8
947 6
946 6
945 6
944 6
943 6
942 6
941 8
940 6
939 10
938 6
937 6
936 6
935 6
934 6
933 8
932 6
931 6
930 6
929 6
928 8
927 6
926 6
925 8
924 8
923 8
922 6
921 6
920 8
919 6
918 10
917 6
916 8
915 6
914 6
913 6
912 8
911 10
910 6
909 6
908 6
907 6
906 8
905 8
904 6
903 8
902 6
901 10
900 6
899 10
898 12
897 8
896 8
895 10
894 8
893 10
892 8
891 10
890 8
889 8
888 8
887 10
886 8
885 10
884 8
883 6
882 6
881 8
880 6
879 8
878 6
877 8
876 6
875 12
874 6
873 8
872 6
871 6
870 8
869 6
868 6
867 8
866 6
865 8
864 6
863 6
862 6
861 6
860 6
859 6
858 6
857 6
856 6
855 8
854 6
853 6
852 6
851 6
850 8
849 6
848 6
847 8
846 8
845 6
844 6
8

In [561]:
abc

array([[3, 3, 4, 2, 3, 3, 2, 2, 2, 1],
       [4, 2, 4, 3, 2, 4, 1, 1, 2, 2],
       [3, 3, 1, 1, 4, 2, 3, 4, 4, 4],
       [3, 1, 3, 4, 1, 3, 4, 1, 3, 4],
       [2, 1, 3, 1, 3, 1, 1, 4, 4, 1],
       [2, 4, 4, 1, 4, 2, 1, 1, 2, 4],
       [2, 4, 4, 1, 4, 1, 3, 3, 3, 4],
       [2, 3, 4, 3, 4, 1, 3, 2, 4, 1],
       [3, 2, 2, 1, 4, 4, 2, 4, 2, 2],
       [3, 4, 4, 1, 3, 1, 1, 2, 3, 1]])

In [562]:
fitness_func(abc)

{(6, 2): 3,
 (0, 7): 2,
 (0, 8): 2,
 (1, 8): 2,
 (2, 0): 2,
 (2, 8): 2,
 (2, 9): 2,
 (4, 6): 2,
 (5, 0): 2,
 (5, 1): 2,
 (5, 2): 2,
 (5, 3): 2,
 (5, 6): 2,
 (6, 0): 2,
 (6, 1): 2,
 (6, 4): 2,
 (6, 6): 2,
 (6, 7): 2,
 (7, 4): 2,
 (8, 4): 2,
 (0, 0): 1,
 (0, 1): 1,
 (0, 2): 1,
 (0, 4): 1,
 (0, 5): 1,
 (0, 6): 1,
 (1, 2): 1,
 (1, 6): 1,
 (1, 7): 1,
 (1, 9): 1,
 (2, 1): 1,
 (2, 2): 1,
 (2, 3): 1,
 (2, 7): 1,
 (3, 0): 1,
 (3, 1): 1,
 (3, 2): 1,
 (3, 9): 1,
 (4, 0): 1,
 (4, 1): 1,
 (4, 2): 1,
 (4, 3): 1,
 (4, 5): 1,
 (4, 7): 1,
 (4, 8): 1,
 (5, 4): 1,
 (5, 7): 1,
 (5, 9): 1,
 (6, 3): 1,
 (6, 5): 1,
 (6, 8): 1,
 (6, 9): 1,
 (7, 0): 1,
 (7, 2): 1,
 (7, 5): 1,
 (7, 6): 1,
 (8, 0): 1,
 (8, 1): 1,
 (8, 2): 1,
 (8, 3): 1,
 (8, 5): 1,
 (8, 8): 1,
 (8, 9): 1,
 (9, 0): 1,
 (9, 1): 1,
 (9, 2): 1,
 (9, 3): 1,
 (9, 5): 1,
 (9, 6): 1,
 (0, 3): 0,
 (0, 9): 0,
 (1, 0): 0,
 (1, 1): 0,
 (1, 3): 0,
 (1, 4): 0,
 (1, 5): 0,
 (2, 4): 0,
 (2, 5): 0,
 (2, 6): 0,
 (3, 3): 0,
 (3, 4): 0,
 (3, 5): 0,
 (3, 6): 0,
 (3,

### Testing the Fitness Function (Internal) Value should be 0 - This section is not needed for the problem

In [626]:
max_range = n*n + 1
best_array = np.reshape(range(1, max_range), (n,n))

In [627]:
best_array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [363]:
sum(fitness_func(best_array).values())

8

In [481]:
n = 10
array = np.random.randint(low=1, high=n+1, size=(n, n))
array

array([[ 8,  5,  4,  1,  3,  7,  4,  2, 10,  7],
       [ 3,  7,  1,  6,  6,  5,  9,  2,  6,  8],
       [ 9,  3,  8, 10,  2,  8,  7,  4, 10,  9],
       [ 2,  6,  1,  1,  5,  1,  9,  4,  9,  5],
       [ 7,  9,  9,  8, 10,  9, 10,  6,  4,  1],
       [ 1,  4,  9,  2,  9,  9,  4,  3,  4,  5],
       [ 2,  6, 10,  7,  3,  2,  1,  8,  6,  4],
       [ 5,  7,  8,  9,  5,  5,  3,  2,  4,  5],
       [ 6, 10,  1,  5,  2,  7,  9,  7,  8,  8],
       [ 4,  3,  1,  6,  2,  5,  6,  9,  3,  2]])

In [482]:
fitness_func(array)

{(2, 1): 2,
 (3, 1): 2,
 (0, 3): 1,
 (0, 4): 1,
 (1, 1): 1,
 (3, 0): 1,
 (0, 0): 0,
 (0, 1): 0,
 (0, 2): 0,
 (1, 0): 0,
 (1, 2): 0,
 (1, 3): 0,
 (1, 4): 0,
 (2, 0): 0,
 (2, 2): 0,
 (2, 3): 0,
 (2, 4): 0,
 (3, 2): 0,
 (3, 3): 0,
 (3, 4): 0,
 (4, 0): 0,
 (4, 1): 0,
 (4, 2): 0,
 (4, 3): 0,
 (4, 4): 0}

### Rough

In [137]:
for index, x in np.ndenumerate(array):
    print(index, x)

(0, 0) 4
(0, 1) 2
(0, 2) 1
(0, 3) 4
(0, 4) 2
(1, 0) 2
(1, 1) 4
(1, 2) 4
(1, 3) 4
(1, 4) 3
(2, 0) 3
(2, 1) 2
(2, 2) 1
(2, 3) 3
(2, 4) 4
(3, 0) 1
(3, 1) 3
(3, 2) 1
(3, 3) 2
(3, 4) 3
(4, 0) 2
(4, 1) 2
(4, 2) 3
(4, 3) 4
(4, 4) 4


In [610]:
a =  np.random.randint(low=1, high=5, size=(n, n))
b =  np.random.randint(low=10, high=50, size=(n, n))

In [611]:
a

array([[4, 3, 3, 4, 2, 2, 4, 4, 1, 3],
       [2, 4, 3, 1, 1, 1, 1, 3, 1, 2],
       [2, 2, 2, 2, 4, 1, 4, 1, 3, 3],
       [2, 1, 1, 2, 1, 1, 3, 4, 4, 3],
       [3, 3, 2, 3, 4, 4, 2, 4, 4, 1],
       [2, 1, 1, 3, 3, 2, 3, 1, 1, 1],
       [2, 4, 1, 1, 4, 4, 3, 1, 2, 2],
       [2, 1, 2, 1, 3, 1, 4, 3, 2, 4],
       [4, 4, 3, 2, 1, 2, 3, 3, 2, 1],
       [4, 3, 1, 4, 4, 2, 2, 3, 3, 2]])

In [612]:
b

array([[41, 17, 28, 45, 13, 33, 25, 12, 13, 28],
       [43, 26, 48, 34, 15, 23, 38, 32, 30, 46],
       [40, 18, 27, 24, 20, 41, 44, 34, 37, 39],
       [44, 31, 10, 46, 40, 36, 46, 46, 20, 40],
       [46, 14, 43, 31, 12, 34, 49, 31, 17, 19],
       [29, 24, 20, 22, 18, 39, 10, 33, 30, 30],
       [40, 20, 20, 34, 37, 15, 28, 47, 26, 31],
       [35, 30, 38, 12, 38, 25, 27, 14, 41, 16],
       [23, 43, 27, 15, 17, 18, 30, 42, 10, 42],
       [36, 28, 38, 42, 13, 36, 19, 32, 16, 20]])

In [615]:
new = np.zeros((10, 10))

In [619]:
for index, x in np.ndenumerate(new):
    if index[0] % 2 == 0:
        new[index] = a[index]
    else:
        new[index] = b[index]


In [620]:
new

array([[ 4.,  3.,  3.,  4.,  2.,  2.,  4.,  4.,  1.,  3.],
       [43., 26., 48., 34., 15., 23., 38., 32., 30., 46.],
       [ 2.,  2.,  2.,  2.,  4.,  1.,  4.,  1.,  3.,  3.],
       [44., 31., 10., 46., 40., 36., 46., 46., 20., 40.],
       [ 3.,  3.,  2.,  3.,  4.,  4.,  2.,  4.,  4.,  1.],
       [29., 24., 20., 22., 18., 39., 10., 33., 30., 30.],
       [ 2.,  4.,  1.,  1.,  4.,  4.,  3.,  1.,  2.,  2.],
       [35., 30., 38., 12., 38., 25., 27., 14., 41., 16.],
       [ 4.,  4.,  3.,  2.,  1.,  2.,  3.,  3.,  2.,  1.],
       [36., 28., 38., 42., 13., 36., 19., 32., 16., 20.]])