## Imprting the Modules

In [1]:
import random
import numpy as np 
import time
import sys

## Agent Class

In [2]:
class Agent:
    
    def __init__(self, n, best_array=False):
        
        self.best_array = best_array
        
        if not self.best_array:
            self.array = np.random.randint(low=1, high=5, size=(n, n))
            self.fitness = 0 
        else:
            max_range = n*n + 1
            self.array = np.reshape(range(1, max_range), (n,n))
            self.fitness = 0
            
        fitness_value_hash = {}
        for index, x in np.ndenumerate(self.array):
            fitness_value_hash[index] = 0
        
        self.fitness_value_hash = fitness_value_hash
        
    def __str__(self):
        return (f"Array: \n {self.array} \nFitness: {self.fitness}")
#         return (f"Fitness: {self.fitness}")

## Get Adjusent Block Function

In [3]:
def get_adjusent(array, i_row, j_column):
    
    neighbours = {}
    
    try:
        left_element = i_row, j_column - 1
        neighbours[left_element] = (array[left_element[0], left_element[1]])

    except IndexError:
        pass
        
    try: 
        right_element = i_row, j_column + 1
        neighbours[right_element] = (array[right_element[0], right_element[1]])
    
    except IndexError:
        pass
        
    try:
        up_element = i_row - 1, j_column
        neighbours[up_element] = (array[up_element[0], up_element[1]])
   
    except IndexError:
        pass
    
    try:
        down_element = i_row + 1, j_column
        neighbours[down_element] = (array[down_element[0], down_element[1]])

    except IndexError:
        pass

    # Removing the negative index(-1) neighbour
    marker = []
    for i in neighbours.keys():
        if -1 in i:
            marker.append(i)
    if marker != []:
        for i in marker:
            del neighbours[i]    

    return neighbours
    
    

## Initiate Agents

In [4]:
def init_agents(population, size):
    
    return [Agent(size) for _ in range(population)]

## Fitness Function

In [5]:
def fitness(agents):
    
    for agent in agents:
        fitness_value_hash = {}
        for index, x in np.ndenumerate(agent.array):

            fitness_value_each_element = 0
            adjusent_to_x = get_adjusent(agent.array, *index)
            for colour in adjusent_to_x.values():
                if colour == x:
                    pass
                else:
                    fitness_value_each_element += 1

            fitness_value_hash[index] = fitness_value_each_element
     #       print(f"Element Index {index}, Fitness Value {fitness_value_each_element}")
        
        agent.fitness_value_hash = fitness_value_hash
        agent.fitness = sum(fitness_value_hash.values())
        
    return agents


## Selection Function 

In [6]:
def selection(agents):
    
    agents = sorted(agents, key=lambda agent: agent.fitness, reverse=True)
    
    agents = agents[:int(.1 * len(agents))]
    
    return agents

## CrossOver Function

In [7]:
def crossover(agents):
    
    offsprings = []
    
    for _ in range((population - len(agents))//2):
        
        parent1 = random.choice(agents)
        parent2 = random.choice(agents)
        
        child1 = Agent(size_of_matrix)
        child2 = Agent(size_of_matrix)
        
        split = random.randint(0, size_of_matrix - 1) 
        
        child1.array = np.concatenate((parent1.array[0:split], parent2.array[split:size_of_matrix]))
        child2.array = np.concatenate((parent2.array[0:split], parent1.array[split:size_of_matrix]))
        
        child1.array = np.transpose(child1.array)
        child2.array = np.transpose(child2.array)
        
        offsprings.append(child1)
        offsprings.append(child2)

        
    agents.extend(offsprings)
    
    return agents

## Mutation Function (Not using it) 

In [8]:
def mutation(agents):
    
    for agent in agents:
        
        for idx, pram in np.ndenumerate(agent.array):
            colour_hash = [1,2,3,4]
            if random.uniform(0, 1) <= 0.3:
                
                present_color = agent.array[idx]
                
                mycol_hash = colour_hash.copy()
                mycol_hash.remove(present_color)
                
                random_color = random.choice(mycol_hash)

#                 print(array)
#                 print(idx, array[idx])
                agent.array[idx] = random_color
#                 print(array)
#                 print("******")
    return agents

### Get the best array 

In [9]:
def get_best_array(size_of_matrix):
    
    best_array = Agent(size_of_matrix, best_array=True)
    best = [best_array]
    fitness(best)
    b_array = best[0]
    max_score_to_stop = b_array.fitness
#     print(best_array.array)
    return max_score_to_stop
    

## Genetic Algorithm

In [10]:
def ga():
    
    max_score_to_stop = get_best_array(size_of_matrix)
    agents = init_agents(population, size_of_matrix)
    time.sleep(3)
    
    for generation in range(generations):
        
        print(f"Since Generation: {generation}, Best Fitness We Got {agents[0].fitness}, Fitness We Are Looking for {max_score_to_stop}")
        
        agents = fitness(agents)
        agents = selection(agents)
        agents = crossover(agents)
        #agents = mutation(agents)
        
        agents = fitness(agents)
        
        time.sleep(.2)
        print("Sleeping..")
        for agent in agents:
            # print(agent.fitness, max_score_to_stop )
            if agent.fitness == max_score_to_stop:
                print("Got the best array")
                print(agent.array)
                print(f"Fitness of the Above Array {agent.fitness}")
                
                sys.exit(0)


## Global Variables (should be under main())

In [11]:
size_of_matrix = 10
population = size_of_matrix * 100
generations = size_of_matrix * 20

## Starting the Algorithm 

In [12]:
ga()

Since Generation: 0, Best Fitness We Got 0, Fitness We Are Looking for 360
Sleeping..
Since Generation: 1, Best Fitness We Got 310, Fitness We Are Looking for 360
Sleeping..
Since Generation: 2, Best Fitness We Got 322, Fitness We Are Looking for 360
Sleeping..
Since Generation: 3, Best Fitness We Got 324, Fitness We Are Looking for 360
Sleeping..
Since Generation: 4, Best Fitness We Got 330, Fitness We Are Looking for 360
Sleeping..
Since Generation: 5, Best Fitness We Got 340, Fitness We Are Looking for 360
Sleeping..
Since Generation: 6, Best Fitness We Got 350, Fitness We Are Looking for 360
Sleeping..
Since Generation: 7, Best Fitness We Got 350, Fitness We Are Looking for 360
Sleeping..
Since Generation: 8, Best Fitness We Got 356, Fitness We Are Looking for 360
Sleeping..
Got the best array
[[3 2 4 2 1 2 4 1 2 3]
 [2 4 2 1 4 1 3 2 3 4]
 [4 3 4 2 1 3 1 3 1 3]
 [2 1 2 4 2 1 2 4 2 4]
 [1 4 1 3 4 3 1 3 4 2]
 [3 2 3 1 2 4 3 2 1 3]
 [4 1 4 2 1 3 1 3 4 2]
 [1 4 1 3 4 2 3 4 3 4]
 [3 2 4

SystemExit: 0

/Users/debnsuma/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
